name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag kassemz/wordpress-cli:latest --tag kassemz/wordpress-cli:${SHORT_SHA}

    - name: Push Docker images
      if: github.event_name == 'push'
      run: |
        docker push kassemz/wordpress-cli:latest
        docker push kassemz/wordpress-cli:${SHORT_SHA}
